#!/bin/bash

#关键步骤失败时退出脚本，避免最后的apk未包含最新提交的代码
function exitIf()
{
	if [ $? -ne 0 ];then
		echo "ERROR_LOG: " $*
		exit 1
	fi
}

if test $# -lt 1; then
	echo Usage: $0 branch_to_review [target_branch]
	echo If target_branch is not provided, it will use the current branch as the default
fi

source=$1;
BR_TO_REVIEW=BR_TO_REVIEW;
if test $# -lt 2; then
	target=$(git branch | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
else
	target=$2;
fi
repo=`git remote -v | head -n1 | awk '{print $1}'`

git fetch -p; exitIf fail to fetch $repo;
git branch -D $BR_TO_REVIEW;
git rev-parse --verify $repo/$source;exitIf fail to find source branch $source;
git checkout -b $BR_TO_REVIEW $repo/$source;

git reset --hard $repo/$source;
git rebase $repo/$target; exitIf fail to rebase branch $source onto $target;
git push $repo $BR_TO_REVIEW:$target
git push $repo :$source;
git checkout $target
