#!/bin/bash

kill -2 $(pgrep grape)

npm run env:init

DIRS="common demo account home rrd premiumplan user uplan monthrise"
for dir in $DIRS; do
	cd src/$dir
	echo $(pwd)
	grape release -cw &
	sleep 0.5
	cd ../..
done

npm run server:localhost

