#!/bin/bash

current_branch=$(git branch | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
upstream=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
remote=$(git config --get branch.$current_branch.remote)


if test -z $upstream; then
	echo "Didn't found any upstream, using current branch name '$current_branch' as default upstream."
	upstream=$remote/$current_branch
	git branch --set-upstream-to=$upstream;exitIfError
fi

function exitIfError()
{
	if test $? -ne 0
	then
		echo "command error, exit"
		exit 1
	fi

}
echo git fetch -p $remote
git fetch -p $remote
exitIfError

echo git rebase $upstream
git rebase $upstream
exitIfError

echo git push $remote
git push $remote
exitIfError

git submodule update
